// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMDKpFOReXCcjCf_HWR1aqSUzwMJr1cdk',
    appId: '1:685123041084:web:503a8ef4de6a3168e69039',
    messagingSenderId: '685123041084',
    projectId: 'meat-ordering',
    authDomain: 'meat-ordering.firebaseapp.com',
    storageBucket: 'meat-ordering.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChgMbXYZKw_pY94HBqDwOHxR-WqR1vDfo',
    appId: '1:685123041084:android:780fecaef3b62cc1e69039',
    messagingSenderId: '685123041084',
    projectId: 'meat-ordering',
    storageBucket: 'meat-ordering.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDzvdVUDpm0JOiTLqlr19EvuSq_a3DGwWw',
    appId: '1:685123041084:ios:98185c7155ddb4f7e69039',
    messagingSenderId: '685123041084',
    projectId: 'meat-ordering',
    storageBucket: 'meat-ordering.appspot.com',
    iosClientId: '685123041084-1iru60556c4klhfkmid613pp2gjlpsea.apps.googleusercontent.com',
    iosBundleId: 'com.example.butcherMeatOrdering',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDzvdVUDpm0JOiTLqlr19EvuSq_a3DGwWw',
    appId: '1:685123041084:ios:5e86a88bca3c36b4e69039',
    messagingSenderId: '685123041084',
    projectId: 'meat-ordering',
    storageBucket: 'meat-ordering.appspot.com',
    iosClientId: '685123041084-mi7bhq2rvk46tdbfka5epb1pu6mfqvvd.apps.googleusercontent.com',
    iosBundleId: 'com.example.butcherMeatOrdering.RunnerTests',
  );
}
